import type { WorldPack } from "./pack-types";

export const ALCHEMY_PACK: WorldPack = {
  packId: "elemental-alchemy",
  packVersion: 2,
  name: "Elemental Alchemy",
  description: "Combine materials based on their properties. Drag one onto another to combine.",
  fieldNames: ["flammable", "wet", "hot", "hard", "sharp", "cold"],
  kinds: [
    {
      id: "wood",
      label: "Wood",
      style: { color: "#a0522d", icon: "🪵" },
      fields: { flammable: true },
    },
    {
      id: "fire",
      label: "Fire",
      style: { color: "#ff6b35", icon: "🔥" },
      fields: { hot: true },
    },
    {
      id: "water",
      label: "Water",
      style: { color: "#4a90d9", icon: "💧" },
      fields: { wet: true, cold: true },
    },
    {
      id: "stone",
      label: "Stone",
      style: { color: "#888", icon: "🪨" },
      fields: { hard: true },
    },
    {
      id: "ash",
      label: "Ash",
      style: { color: "#777", icon: "🌫️" },
      fields: {},
    },
    {
      id: "steam",
      label: "Steam",
      style: { color: "#ccc", icon: "♨️" },
      fields: { hot: true, wet: true },
    },
    {
      id: "obsidian",
      label: "Obsidian",
      style: { color: "#1a1a2e", icon: "🔲" },
      fields: { hard: true, sharp: true },
    },
    {
      id: "mud",
      label: "Mud",
      style: { color: "#8b5e3c", icon: "🟫" },
      fields: { wet: true },
    },
  ],
  edgeTypes: [],
  actions: [
    // Wood + Fire → Ash (wood consumed/transformed, fire persists)
    {
      id: "ignite",
      label: "Ignite",
      description: "Flammable material catches fire and becomes ash",
      context: { kind: "wood" },
      target: { kind: "fire" },
      trigger: "combine",
      when: ["and",
        ["get", "contextFields", "flammable"],
        ["get", "targetFields", "hot"],
      ],
      do: [
        { type: "setKind", card: "context", kind: "ash" },
        { type: "setText", card: "context", text: "Ash" },
        { type: "removeField", card: "context", key: "flammable" },
      ],
    },
    // Fire + Water → Steam (fire becomes steam, water consumed)
    {
      id: "extinguish",
      label: "Extinguish",
      description: "Water extinguishes fire, producing steam",
      context: { kind: "fire" },
      target: { kind: "water" },
      trigger: "combine",
      when: ["and",
        ["get", "contextFields", "hot"],
        ["get", "targetFields", "wet"],
      ],
      do: [
        { type: "setKind", card: "context", kind: "steam" },
        { type: "setText", card: "context", text: "Steam" },
        { type: "setKind", card: "target", kind: null },
        { type: "setText", card: "target", text: "(consumed)" },
        { type: "removeField", card: "target", key: "wet" },
        { type: "removeField", card: "target", key: "cold" },
      ],
    },
    // Stone + Water → Mud (stone transformed, water consumed)
    {
      id: "erode",
      label: "Erode",
      description: "Water erodes stone into mud over time",
      context: { kind: "stone" },
      target: { kind: "water" },
      trigger: "combine",
      when: ["and",
        ["get", "contextFields", "hard"],
        ["get", "targetFields", "wet"],
      ],
      do: [
        { type: "setKind", card: "context", kind: "mud" },
        { type: "setText", card: "context", text: "Mud" },
        { type: "removeField", card: "context", key: "hard" },
        { type: "setKind", card: "target", kind: null },
        { type: "setText", card: "target", text: "(consumed)" },
      ],
    },
    // Stone + Fire → Obsidian (stone transformed, fire persists)
    {
      id: "forge",
      label: "Forge",
      description: "Intense heat transforms stone into obsidian",
      context: { kind: "stone" },
      target: { kind: "fire" },
      trigger: "combine",
      when: ["and",
        ["get", "contextFields", "hard"],
        ["get", "targetFields", "hot"],
      ],
      do: [
        { type: "setKind", card: "context", kind: "obsidian" },
        { type: "setText", card: "context", text: "Obsidian" },
      ],
    },
    // Wood + Water → Wet Wood (flammable removed, wet added)
    {
      id: "soak",
      label: "Soak",
      description: "Water soaks wood, making it resistant to fire",
      context: { kind: "wood" },
      target: { kind: "water" },
      trigger: "combine",
      when: ["and",
        ["get", "contextFields", "flammable"],
        ["get", "targetFields", "wet"],
      ],
      do: [
        { type: "removeField", card: "context", key: "flammable" },
        { type: "setField", card: "context", key: "wet", value: true },
        { type: "setText", card: "context", text: "Wet Wood" },
      ],
    },
    // Mud + Fire → Stone (kiln firing)
    {
      id: "fire-mud",
      label: "Fire",
      description: "Heat dries mud into stone",
      context: { kind: "mud" },
      target: { kind: "fire" },
      trigger: "combine",
      when: ["and",
        ["get", "targetFields", "hot"],
        ["get", "contextFields", "wet"],
      ],
      do: [
        { type: "setKind", card: "context", kind: "stone" },
        { type: "setText", card: "context", text: "Stone" },
        { type: "removeField", card: "context", key: "wet" },
      ],
    },
    // Ash + Water → Mud
    {
      id: "ash-water",
      label: "Mix",
      description: "Ash absorbs water to form mud",
      context: { kind: "ash" },
      target: { kind: "water" },
      trigger: "combine",
      when: ["get", "targetFields", "wet"],
      do: [
        { type: "setKind", card: "context", kind: "mud" },
        { type: "setText", card: "context", text: "Mud" },
        { type: "setKind", card: "target", kind: null },
        { type: "setText", card: "target", text: "(consumed)" },
      ],
    },
    // Obsidian + Water → Stone (thermal shock)
    {
      id: "cool-obsidian",
      label: "Cool",
      description: "Cold water cracks obsidian back into stone",
      context: { kind: "obsidian" },
      target: { kind: "water" },
      trigger: "combine",
      when: ["and",
        ["get", "contextFields", "hard"],
        ["get", "targetFields", "cold"],
      ],
      do: [
        { type: "setKind", card: "context", kind: "stone" },
        { type: "setText", card: "context", text: "Stone" },
        { type: "removeField", card: "context", key: "sharp" },
        { type: "setKind", card: "target", kind: null },
        { type: "setText", card: "target", text: "(consumed)" },
      ],
    },
  ],
};
