import type { WorldPack } from "./pack-types";

export const ALCHEMY_PACK: WorldPack = {
  packId: "elemental-alchemy",
  packVersion: 3,
  name: "Elemental Alchemy",
  description: "Combine materials based on their properties. Drag one onto another to combine.",
  fieldNames: ["flammable", "wet", "hot", "hard", "sharp", "cold"],
  kinds: [
    { id: "wood",     label: "Wood",     style: { color: "#a0522d", icon: "🪵" }, fields: { flammable: true } },
    { id: "fire",     label: "Fire",     style: { color: "#ff6b35", icon: "🔥" }, fields: { hot: true } },
    { id: "water",    label: "Water",    style: { color: "#4a90d9", icon: "💧" }, fields: { wet: true, cold: true } },
    { id: "stone",    label: "Stone",    style: { color: "#888",    icon: "🪨" }, fields: { hard: true } },
    { id: "ash",      label: "Ash",      style: { color: "#777",    icon: "🌫️" }, fields: {} },
    { id: "steam",    label: "Steam",    style: { color: "#ccc",    icon: "♨️" }, fields: { hot: true, wet: true } },
    { id: "obsidian", label: "Obsidian", style: { color: "#1a1a2e", icon: "🔲" }, fields: { hard: true, sharp: true } },
    { id: "mud",      label: "Mud",      style: { color: "#8b5e3c", icon: "🟫" }, fields: { wet: true } },
  ],
  edgeTypes: [],
  actions: [
    {
      id: "ignite",
      label: "Ignite",
      description: "Flammable material catches fire and becomes ash",
      context: { kind: "wood" },
      target: { kind: "fire" },
      trigger: "combine",
      run: ["if",
        ["and", ["get", ["var", "contextFields"], "flammable"], ["get", ["var", "targetFields"], "hot"]],
        ["array",
          ["call", ["var", "setKind"], ["var", "context"], "ash"],
          ["call", ["var", "removeField"], ["var", "context"], "flammable"],
        ],
        null,
      ],
    },
    {
      id: "extinguish",
      label: "Extinguish",
      description: "Water extinguishes fire, producing steam",
      context: { kind: "fire" },
      target: { kind: "water" },
      trigger: "combine",
      run: ["if",
        ["and", ["get", ["var", "contextFields"], "hot"], ["get", ["var", "targetFields"], "wet"]],
        ["array",
          ["call", ["var", "setKind"], ["var", "context"], "steam"],
          ["call", ["var", "removeCard"], ["var", "target"]],
        ],
        null,
      ],
    },
    {
      id: "erode",
      label: "Erode",
      description: "Water erodes stone into mud",
      context: { kind: "stone" },
      target: { kind: "water" },
      trigger: "combine",
      run: ["if",
        ["and", ["get", ["var", "contextFields"], "hard"], ["get", ["var", "targetFields"], "wet"]],
        ["array",
          ["call", ["var", "setKind"], ["var", "context"], "mud"],
          ["call", ["var", "removeField"], ["var", "context"], "hard"],
          ["call", ["var", "removeCard"], ["var", "target"]],
        ],
        null,
      ],
    },
    {
      id: "forge",
      label: "Forge",
      description: "Intense heat transforms stone into obsidian",
      context: { kind: "stone" },
      target: { kind: "fire" },
      trigger: "combine",
      run: ["if",
        ["and", ["get", ["var", "contextFields"], "hard"], ["get", ["var", "targetFields"], "hot"]],
        ["array",
          ["call", ["var", "setKind"], ["var", "context"], "obsidian"],
        ],
        null,
      ],
    },
    {
      id: "soak",
      label: "Soak",
      description: "Water soaks wood, making it resistant to fire",
      context: { kind: "wood" },
      target: { kind: "water" },
      trigger: "combine",
      run: ["if",
        ["and", ["get", ["var", "contextFields"], "flammable"], ["get", ["var", "targetFields"], "wet"]],
        ["array",
          ["call", ["var", "removeField"], ["var", "context"], "flammable"],
          ["call", ["var", "setField"], ["var", "context"], "wet", true],
          ["call", ["var", "setText"], ["var", "context"], "Wet Wood"],
        ],
        null,
      ],
    },
    {
      id: "fire-mud",
      label: "Fire",
      description: "Heat dries mud into stone",
      context: { kind: "mud" },
      target: { kind: "fire" },
      trigger: "combine",
      run: ["if",
        ["and", ["get", ["var", "contextFields"], "wet"], ["get", ["var", "targetFields"], "hot"]],
        ["array",
          ["call", ["var", "setKind"], ["var", "context"], "stone"],
          ["call", ["var", "removeField"], ["var", "context"], "wet"],
        ],
        null,
      ],
    },
    {
      id: "ash-water",
      label: "Mix",
      description: "Ash absorbs water to form mud",
      context: { kind: "ash" },
      target: { kind: "water" },
      trigger: "combine",
      run: ["if",
        ["get", ["var", "targetFields"], "wet"],
        ["array",
          ["call", ["var", "setKind"], ["var", "context"], "mud"],
          ["call", ["var", "removeCard"], ["var", "target"]],
        ],
        null,
      ],
    },
    {
      id: "cool-obsidian",
      label: "Cool",
      description: "Cold water cracks obsidian back into stone",
      context: { kind: "obsidian" },
      target: { kind: "water" },
      trigger: "combine",
      run: ["if",
        ["and", ["get", ["var", "contextFields"], "hard"], ["get", ["var", "targetFields"], "cold"]],
        ["array",
          ["call", ["var", "setKind"], ["var", "context"], "stone"],
          ["call", ["var", "removeField"], ["var", "context"], "sharp"],
          ["call", ["var", "removeCard"], ["var", "target"]],
        ],
        null,
      ],
    },
  ],
};
